# Kubernetes/configurator.service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: -deployment
  labels:
    app: 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: 
        image: your-docker-repo/
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        # Add other environment variables as needed
